### ISSUE TITLE
Create back-port versions?

### ISSUE THREAD

**Issue by zerothi** [tfrederiksen/inelastica#16]
One can add tags to prior commits which may accommodate having the releases (1.0 and 1.1) here on github as well (for completeness sake).

Here are the hashes:
- 1.0: faeb8442f7697e0f1bc85e8283bbb78b6bc35a7d
- 1.1: 899a0512b7f8ed4885dcbf3bdec9d87c220d3801

A word of advice. Use `git tag -a` and not just `git tag`, see here for some info:
https://stackoverflow.com/questions/4971746/why-should-i-care-about-lightweight-vs-annotated-tags

**Comment by tfrederiksen** [comment]
Thanks for the suggestion. I think I managed to add these two annotated tags.
