### ISSUE TITLE
Use the examples of AuH2

### ISSUE THREAD

**Issue by QinglangL** [tfrederiksen/inelastica#44]
In the examples of AuH2/L9.68/TSrun, I run the command    $EigenChannels ECrun, and I get a error:

SiestaIO.ReadTSHS: Reading TSHS header from ./Chain.TSHS
STOP Unsupported TSHS version file
 
So, what should I do to to solve this?

**Comment by tfrederiksen** [comment]
Which versions of `Inelastica` and `TranSIESTA` are you using?

**Comment by QinglangL** [comment]
Inelastica is 1.3.3, and transiesta is 4.1

**Comment by tfrederiksen** [comment]
This combination should work. But are you sure you are using `Inelastica-1.3.3`? I doubt it because the line with `SiestaIO.ReadTSHS` was modified to print `io.siesta.ReadTSHS` in `v1.3.3`. Please also check that the file `Chain.TSHS` exists and is not corrupt. In any case it could be helpful to see the full log files.

**Comment by QinglangL** [comment]
I am sure that.   /Downloads/inelastica-1.3.3/Examples/AuH2/L9.68/TSrun  and this is my address of inelastica.  I try to open the Chain.TSHS, but it is empty. So I copy the Electrode.TSHS from the ELEC folder and rename it with Chain.TSHS.
     Then I try again the command  $EigenChannels ECrun  , it  gives me an error:

SiestaIO.ReadXVFile: Reading ./Chain.XV
SiestaIO.HS.__init__: Reading ././ELEC/Electrode.TSHS
Found 4 atoms, (1620, 60) orbitals in super-, unit-cell
SiestaIO.HS.__init__: Reading ././ELEC/Electrode.TSHS
Found 4 atoms, (1620, 60) orbitals in super-, unit-cell
SiestaIO.HS.__init__: Reading ./Chain.TSHS
Found 4 atoms, (1620, 60) orbitals in super-, unit-cell
GF: UseBulk= True
Traceback (most recent call last):
  File "/home/qing/anaconda3/envs/inelastica/bin/EigenChannels", line 11, in <module>
    Module.main(options)
  File "/home/qing/anaconda3/envs/inelastica/lib/python2.7/site-packages/Inelastica/EigenChannels.py", line 127, in main
    BufferAtoms=options.buffer)
  File "/home/qing/anaconda3/envs/inelastica/lib/python2.7/site-packages/Inelastica/NEGF.py", line 516, in __init__
    self.DeviceOrbs = [self.HS.lasto[DeviceAtoms[0]-1]+1, self.HS.lasto[DeviceAtoms[1]]]
IndexError: index 8 is out of bounds for axis 0 with size 5

      And I check the file, not find the index of 8.  Now , what should I do ?

**Comment by QinglangL** [comment]
I am sure that.   /Downloads/inelastica-1.3.3/Examples/AuH2/L9.68/TSrun  and this is my address of inelastica.  I try to open the Chain.TSHS, but it is empty. So I copy the Electrode.TSHS from the ELEC folder and rename it with Chain.TSHS.
 Then I try again the command  $EigenChannels ECrun  , it  gives me an error:


SiestaIO.ReadXVFile: Reading ./Chain.XV
SiestaIO.HS.init: Reading ././ELEC/Electrode.TSHS
Found 4 atoms, (1620, 60) orbitals in super-, unit-cell
SiestaIO.HS.init: Reading ././ELEC/Electrode.TSHS
Found 4 atoms, (1620, 60) orbitals in super-, unit-cell
SiestaIO.HS.init: Reading ./Chain.TSHS
Found 4 atoms, (1620, 60) orbitals in super-, unit-cell
GF: UseBulk= True
Traceback (most recent call last):
File "/home/qing/anaconda3/envs/inelastica/bin/EigenChannels", line 11, in 
Module.main(options)
File "/home/qing/anaconda3/envs/inelastica/lib/python2.7/site-packages/Inelastica/EigenChannels.py", line 127, in main
BufferAtoms=options.buffer)
File "/home/qing/anaconda3/envs/inelastica/lib/python2.7/site-packages/Inelastica/NEGF.py", line 516, in init
self.DeviceOrbs = [self.HS.lasto[DeviceAtoms[0]-1]+1, self.HS.lasto[DeviceAtoms[1]]]
IndexError: index 8 is out of bounds for axis 0 with size 5


  And I check the file, not find the index of 8.  Now , what should I do ?

**Comment by tfrederiksen** [comment]
You can't replace `Chain.TSHS` by `Electrode.TSHS` - these are two different systems, which explains why you get the index error above. Did you try to rerun `TranSIESTA`? Make sure this calculation finishes correctly.

**Comment by tfrederiksen** [comment]
OK, the issue is then your `TranSIESTA` calculation, not `EigenChannels`.

**Comment by bookkiy** [comment]
Hi,my name is Bookkiy .In the examples of CO/Cu(111), after running the command “STM -F 64 -L 87 -n 1 -x 5 -y 5 STM5x5”,I get the STMimage.nc file .But I have no idea how to draw the the STM image.The version of Inelastica is 3.0, and transiesta is siesta-MAX-1.2.1
 So, how can I draw the STM image using the STMIimage.nc file? 
Thank you very much and looking forward to your replay.

**Comment by tfrederiksen** [comment]
> Hi,my name is Bookkiy .In the examples of CO/Cu(111), after running the command “STM -F 64 -L 87 -n 1 -x 5 -y 5 STM5x5”,I get the STMimage.nc file .But I have no idea how to draw the the STM image.The version of Inelastica is 3.0, and transiesta is siesta-MAX-1.2.1 So, how can I draw the STM image using the STMIimage.nc file? Thank you very much and looking forward to your replay.

You can use Mathematica to draw the images, please have a look here:
https://github.com/tfrederiksen/inelastica/tree/master/Examples/STMimage
