### ISSUE TITLE
local heating in Inelastica

### ISSUE THREAD

**Issue by zhikai-zhao** [tfrederiksen/inelastica#49]
dear developments and users

I used Inelastica, the python tool of siesta/transiesta, to calculate local heating in molecular junction. After running Inelastica, there are some information about heating for a certain phonon mode, such as " heating 2.934396e+10 (1/(sV))".

 My question is what the value and the unit mean? For a bias voltage, for example 0.5V, what is the power of this phonon mode that transfers the energy into heat?

thanks in advance.

**Comment by tfrederiksen** [comment]
The key quantity being reported here is `MM.trace(MM.mm(M, GF1.AL, M, GF2.AR))`. In the LOE approach this expresses the rate of phonon emission per unit of applied bias voltage. Please see Eqs. (49)-(50) in [PRB 75, 205413 (2007)](https://journals.aps.org/prb/abstract/10.1103/PhysRevB.75.205413).

In your example at `V=0.5V` the emission rate would thus be `~ 15 phonons/ns`.

**Comment by zhikai-zhao** [comment]
Frederiksen, thanks for your reply.
I have another question, can the rate of phonon absorption be calculated by Inelastica?

**Comment by tfrederiksen** [comment]
Hi @zhikai-zhao, phonon absorption is related to the electron-hole pair damping rate which, in the LOE, is expressed in terms of the factor `MM.trace(MM.mm(M, GF1.A, M, GF2.A))`. See Eq. (48) in the paper mentioned above. This quantity is also in the output files.

**Comment by zhikai-zhao** [comment]
Hi Frederiksen, in the output files, the unit of e-h damping is (1/s), should e-h damping be bias-independent? 
 For example, 3.0e10 (1/s) means that the absorption rate is about ~30 phonons/ns. Is that right?

Thanks so much

**Comment by tfrederiksen** [comment]
In principle both the emission rate and e-h damping are bias-dependent (involving an integral over energy), but in the LOE approach this is simplified by evaluating the rates at the voltage threshold for phonon emission, that is `V=\hbar\omega_i` (or simply `V=0` in the original LOE-WBA).
