### ISSUE TITLE
failure of installing Inelastica  

### ISSUE THREAD

**Issue by zhuolingjiang** [tfrederiksen/inelastica#55]
The versions of packages are python 2.7, numpy-1.15.4, netCDF4-1.4.2, scipy-1.1.0, and Inelastica-1.3.5.

 the install commands are as follows

python2.7  setup.py install   --prefix=/work/phyjia/software/python2.7/
 the output is as follows
[out.log](https://github.com/tfrederiksen/inelastica/files/3466286/out.log)

**Comment by zerothi** [comment]
The output clarifies that you need to compile with `-fPIC` flag in your `CFLAGS`/`FFLAGS`.
