### ISSUE TITLE
XSF file displaying different lattice vectors from RUN.fdf ?

### ISSUE THREAD

**Issue by el-abed** [tfrederiksen/inelastica#57]
Good evening all
First of all happy holidays! As it is my first time let me introduce myself before addressing my issue:
 
My name is El-Abed Haidar. I am currently studying my PhD within the condensed matter theory group at the University of Sydney. I was wondering if anyone could answer me this insight question from Inelastica. The questions are as follow:
1- When using Eigenchannel utility, I noticed the MPSH states are given within an entire different unit cell from the input fdf file (RUN.fdf) I have introduced. It might sound a stupid question but could that software give an alternative unit cell than the one used in RUN.fdf? 
attached here is the fdf file in word format.
[RUNfdf file.docx](https://github.com/tfrederiksen/inelastica/files/4079933/RUNfdf.file.docx)

2- If not why was those parameters suggested in the VESTA figure below in the first place?
![VESTA](https://user-images.githubusercontent.com/18545471/72658045-b2f3fe80-39ff-11ea-992a-cc543ba968af.JPG)

3- In other words would the software Eigenchannel convert my RUN.fdf lattice vectors always into rectangular unit cells a b and c?

Thank you ! Looking forward to all comments and replies!
EL-abed

**Comment by jonaslb** [comment]
Hi El-Abed,
The EigenChannels utility should not alter the unit cell.
It does however read the coordinates from the systemlabel.XV file which, generally speaking, can differ from the input fdf-file if Siesta did any optimization (but that's not specified in your input so it's not the issue).

Your input fdf-file contains the following section:
```
LatticeConstant       1.0 Ang 
%block LatticeVectors
44.7999992371         0.0000000000         0.0000000000
0.0000000000        32.7999992371         0.0000000000
0.0000000000         0.0000000000        56.4000015259
%endblock LatticeVectors
```
which would seem to be in agreement with the lattice parameters reported in your screenshot. 

Since you say that you have specified another cell, perhaps this is a matter of having used the wrong fdf-file for calculation input?

/ Jonas

PS. You don't have to put your fdf-file into a word-file ;)

**Comment by el-abed** [comment]
Thank you very much for the reply.
I apologise for keeping the XSF lattice vectors into the RUN.fdf

 I have been trying to looking at both lattice vectors of the XSF file and RUN.fdf and instead of putting the original vectors i kept (i apologise) the XSF vectors. Notice the following
[problem.zip](https://github.com/tfrederiksen/inelastica/files/4082132/problem.zip)

IN the XV file i will get those numbers which should be the same as the input fdf file but in Bohr units:
![image](https://user-images.githubusercontent.com/18545471/72673113-e2674180-3ab9-11ea-9ddf-a7d90b624478.png)



those lattice vectors in the XV file should be equivalent to the fdf file below
![image](https://user-images.githubusercontent.com/18545471/72673104-bf3c9200-3ab9-11ea-95a4-950b751d3cd8.png)

However as I have shown in the first post, it is completely different. 
As a reminder here is one of the XSF files opened in VESTA which showed a rectangular cell unlike the fdf and XV files:

![image](https://user-images.githubusercontent.com/18545471/72673155-80f3a280-3aba-11ea-8588-40ee1385fe63.png)


Any reason?
Thanks for the PS Jonas but for some reason i could not upload the fdf file. Not sure but hopefully my zip folder opens and would like to know your thoughts!
Thank you again and looking forward to your reply!
EL-Abed

**Comment by jonaslb** [comment]
Ah, the disagreement is more apparent now. 

EigenChannels does all of it's calculations on a rectangular grid extending 5Å further than wherever the atoms are. This happens regardless of the unit cell used. 
It doesn't write the unit cell to the XSF files, but the extent of this data grid instead. That seems to be what VESTA reports as the lattice in this case.

The `calcWF`-function where you can see that a rectangular grid is used is [here](https://github.com/tfrederiksen/inelastica/blob/master/Inelastica/EigenChannels.py#L235) and the `writeXSF` function where you can see that the cell is not actually being written, but the rectangular grid extents are, is [here](https://github.com/tfrederiksen/inelastica/blob/master/Inelastica/EigenChannels.py#L508).

I'm not the author of the EigenChannels tool though so I can't exactly say why this particular choice was made, but I imagine that properly handling periodic boundary conditions is tricky. So this could simply be a consequence of simplifying the implementation. 
I imagine you are interested in what happens inside your molecule regardless, where you don't (I suppose) have overlap with the periodic images.

**Comment by el-abed** [comment]
Thank you very much for the fruitful reply!
I understand that i am using the software to just observe the MPSH states.  I am mostly interested in the MPSH states but was wondering if XSF files also suggest unit cell dimensions because that would make sense and is really interesting to redo the calculations based on those lattice vectors in XSF file.

I understand why you wont be able to answer the following question then:
Would you reckon or recommend to use the suggested unit vectors in the XSF files? 
So I am hoping anyone could answer that. Or are they entirely wrong? Why or why not?
Thank you and looking forward to all comments and replies!
EL-abed

**Comment by jonaslb** [comment]
The dimensions in the XSF file are *not* a unit cell, they are the extents of the data grid, it's just that VESTA wrongly reports it as a lattice. 
If you specify a smaller device region (eg. just the molecule) to EigenChannels you should see that the grid becomes correspondingly smaller.

**Comment by tfrederiksen** [comment]
Dear @el-abed and @jonaslb, thanks for your exchange. Just to confirm what Jonas said: Indeed `EigenChannels` computes states on a regular grid, defined by the extension of the orbitals in the selected device region. This grid is not really related to the lattice vectors.

**Comment by el-abed** [comment]
Thank you @tfrederiksen very much! It was just curiosity and my surprise that the unit cell in VESTA displayed a potential unit cell suitable for my system other than the vectors suggested in the RUN.fdf
Thus my questions in this thread. Just curious would it be usable or not? 
Otherwise thank you both again for your time and comments! As my first time here Im glad i learnt a lot!

**Comment by tfrederiksen** [comment]
Not usable, it would be a coincidence! I think we can close the issue now.
