### ISSUE TITLE
Inquiry about EigenChannels limitations

### ISSUE THREAD

**Issue by el-abed** [tfrederiksen/inelastica#58]
Good afternoon to whom it may concern,
I was trying to calculate the EigenChannels for different phospherene/graphene systems with different number of atoms. 
Some would end successfully. But as the number of atoms increases ( by a 100 or so) the job would be killed.
I wanted to ask if there are limits to EigenChannels? If not, can it be run parallel?
thank you very much and looking forward to your thoughts

**Comment by tfrederiksen** [comment]
It could be that you are running out of memory for large systems, but without more info it is difficult to say. Feel free to share more details here about a problematic run.

Generally speaking, to limit the computational burden of `EigenChannels` it is essential to keep the device region to a minimum. This is controlled with the keywords `-F` and `-L`(or equivalently `--DeviceFirst` and `--DeviceLast`).

**Comment by el-abed** [comment]
Thank you very much Thomas for the reply.
I have managed to run in parallel the system with 8 cores and the run finished successfully.
I was wondering from a physical stand point, shouldn’t it be more wisely to study the entire system not only the scattering region to find out if conductance does take place or not?
So for example if the eigenchannels runs through out the entire system is an indication of high conductance.
Where can I read more about such insight?
Thank you very much again and hope to read your reply.
EL-abed

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
