### ISSUE TITLE
Inquiry about Eigenchannel script

### ISSUE THREAD

**Issue by el-abed** [tfrederiksen/inelastica#59]
Good evening,
I was wondering if the Eigenchannel script would run properly despite not having the following: (TS.TBT.Npoints, TS.TBT.Emin, TS.TBT.Emax) SiestaIO

which was recommended based on the website: http://dipc.ehu.es/frederiksen/tstutorial/index.php/Inelastica

The reason i am asking is because despite the run looking normal:
[update1.txt](https://github.com/tfrederiksen/inelastica/files/4768232/update1.txt)

i got no eigenchannels around the fermi level and I want to make sure that everything is correct.

I guess in other words my question is how to properly know if the script worked properly?

Thank you very much and looking forward to your reply.
EL-abed

**Comment by tfrederiksen** [comment]
Dear El-abed,

Your output file looks reasonable and I expect that the code has generated `XSF` files in the specified folder `NEWscattering`, both for the eigenchannels at `E=0` as well as the molecular MPSH states at their corresponding energies.

The comment in the wiki-page you refer to is no longer a constraint (it only applied to an old version of Inelastica).

**Comment by el-abed** [comment]
Good evening again,
Thank you for the reply first of all. I have a couple of questions:
1- I am assuming when you said E=0, it means the MPSH wrt the Fermi level ?
Because i used the following command:
EigenChannels -F 381 -L 760 -M 0.5 NEWscattering2/ >update2.txt
to specify first and last atom and MPSH at 0.5 eV away from Fermi energy.

2- What is the difference between UP.XSF and XSF ?
Is it the fact UP represents up spin ones while XSF could be both? If so where could I find the energy of the UP one?

3- Have you, based on your experience, encountered nonphysical results despite the script working just fine? Because for EigenChannels to work a proper siesta, transiesta and tbtrans runs should be completed. If you could kindly share your thoughts that would be highly appreciated. 
Thank you and looking forward to your reply.
EL-abed

**Comment by tfrederiksen** [comment]
1. Yes, energies are expressed wrt. the Fermi energy in Inelastica. The flag `-M` specifies you want all MPSH states up to 0.5 eV away from the Fermi energy (if any) written to files.
2. `XSF` is the file format of the wave functions. UP/ DOWN are appended to the filename for spin-polarized calculations.
3. Please formulate the question more specifically, I cannot help in such general terms.

**Comment by el-abed** [comment]
Thank you very much for your replies.  Really appreciate your time!
As for the last question:
This system is a graphene phospherene system which based on tbtrans has showed transmission at the Fermi level. One would predict to find eigenchannels at either HOMO or LUMO states. 
However, this was not the case at all. 
My question was about the script EIGENCHANNELS if any user has got contradictory results to tbtrans? Which is why i asked if you (based on your experience) or any user  had contradictory results?
Hope that made more sense. Looking forward to your reply!

**Comment by tfrederiksen** [comment]
I am not aware of any contradictions with `tbtrans`. Remember that the energy of the eigenchannels is set by the user and can take any value within the band width of the electrode (in contrast to MPSH).

**Comment by el-abed** [comment]
I agree with your statement because i found eigenchannels at LUMO and HOMO + 6 and even above when using the following:
/EigenChannels -F 381 -L 760 -M 1 NEWscattering2/ >update2.txt

However, finding transmission at zero volt at the Fermi energy contradicts such MPSH or Eigenchannel states which is why I was wondering about the contraction. Should I be using a different command in this case ? For instance -e? Is that from the Fermi energy also?

**Comment by tfrederiksen** [comment]
Sorry for this late reply. In order to compute eigenchannels at a given energy (selected with the `-e` keyword) there has to be some non-zero transmission. On the other hand, the MPSH are eigenstates of a (finite but arbitrarily large) device Hamiltonian (ie. no electrodes) and their energies are an outcome of the calculation. The MPSH states are not strictly related to the transport calculation, but can sometimes - under certain conditions - be linked to resonances in the transmission function.

**Comment by el-abed** [comment]
Thank you very much for the reply. Of course I am assuming non-zero transmission:

  1.  A computational question: In terms of MPSH vs eigenchannel commands does that differ other than the choice of atoms? In other words for MPSH based on your recent email I should specify the scattering device (using -F and -L) while the eigenchannels I should not. Is that correct?
  2.  A conceptual question: So if MPSH states are not strictly related to transmission it is more advisable to find the Eigenchannel. Is that correct? I was genuinely surprised since I thought you would be able to find the HOMO-LUMO gap from MPSH and that helps explain the transmission.
  3.  If 2) is yes, what information could I extract from Eigenchannels other than whether the states are delocalized? No energy information is shown. Only Up and down or am I missing something?

Thank you very much and looking forward to your reply.
EL-abed

El-abed Haidar | Doctor of Philosophy (Science)
 Condensed Matter Theory (CMT) Group| School of Physics
 THE UNIVERSITY OF SYDNEY  | NSW | 2006

**Comment by el-abed** [comment]
Also what kind of conditions should one be aware of?

El-abed Haidar | Doctor of Philosophy (Science)
 Condensed Matter Theory (CMT) Group| School of Physics
 THE UNIVERSITY OF SYDNEY  | NSW | 2006

**Comment by tfrederiksen** [comment]
The parameters `-F` and `-L` defines the device region. In the case of the eigenchannels they determine where the (delocalized) wave function will be visualized.

For MPSH, you can obtain the HOMO-LUMO states _if_ your system has a well-defined "molecular" center and you choose exactly this region to be the device. Therefore, MPSH analysis of an infinite nanoribbon is probably not a meaningful thing to do.
