### ISSUE TITLE
Using the examples of CO/Cu(111) for STMimage

### ISSUE THREAD

**Issue by bookkiy** [tfrederiksen/inelastica#67]
Thank you very much for your reply,but I have a new question.
In the examples of CO/Cu(111), after running the command “STM -F 64 -L 87 -n 1 -x 5 -y 5 STM5x5”,I get the STMimage.nc file .
The version of Inelastica is 3.0, and transiesta is siesta-MAX-1.2.1.
I use the Mathematica notebook of AnalyzeSTMimage.nb to draw the STM images,but when I import the STMimage.nc file,there is no data,I don't khnow where the error is? Please help me to find out the error.
The output in Mathematica is shown as below.
[STMimage](https://user-images.githubusercontent.com/72913696/144162438-fae6a721-76f0-4812-bf22-c4910571a784.jpg)
And I also upload the  STM.txt file which is converted from the STMimage.nc file. 
[STM.txt](https://github.com/tfrederiksen/inelastica/files/7630438/STM.txt)
Thanks again!

**Comment by tfrederiksen** [comment]
By looking at `STM.txt` it appears to me that your `nc` file from Inelastica contains all the required data for visualization. Maybe it is an issue with Mathematica. Which version are you using? Note that `Examples/STMimage` contains three notebooks for different Mathematica versions.

**Comment by bookkiy** [comment]
Yes! That' right, it is the problem of Mathematica version, I chose another version of notebook and get the  STM image.
Thank you much for your time and reply!
