### ISSUE TITLE
Using the examples of CO/Cu(111) for STMimage

### ISSUE THREAD

**Issue by qiezi00** [tfrederiksen/inelastica#69]
Dear all,
I am experiencing an issue with the CO/Cu(111) examples.  Specifically, after executing the command "STM -F 64 -L 87 -n 1 -x 1 -y 1 STM1x1", the calculation seems to get stuck at the ''Mode propagation starts'' stage and does not proceed any further.  I have not received any error messages or warnings.
Could you please advise me on what steps I can take to resolve this issue?
Thank you very much! I am looking forward to your reply.
<img width="562" alt="stm" src="https://user-images.githubusercontent.com/129371106/228789869-55438f7b-f09b-4bef-b00a-9a5ffe7cd05d.png">

**Comment by qiezi00** [comment]
I apologize for the inconvenience.   The problem has been resolved.   I realized that I forgot to install Scipy,  after installing it, everything is working properly now.

**Comment by tfrederiksen** [comment]
No worries, thanks for your interest in Inelastica.
